name = "RPOMDPs"
uuid = "79d4483c-aee9-4fa5-953b-21346e5b117c"
authors = ["Merlijn Krale"]
version = "1.0.0-DEV"

[compat]
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
